### ISSUE TITLE
[suggestion] make version for Moodle 2.2 and 2.3

### ISSUE THREAD

**Issue by germanvaleroelizondo** [hit-moodle/moodle-mod_hotquestion#18]
This is a nice plugin. Some people would like it to be available for Moodle 2.2 and 2.3 branches.
If it were possible.
Thanks

**Comment by sunner** [comment]
Good suggestion. Have you ever tried it on Moodle 2.2 or 2.3? As I know these updates should not affect hotquestion.

I just changed my job two months ago. Perhaps I will not update these projects often any more.

**Comment by daveyboond** [comment]
I have been testing this on Moodle 2.2. It mostly works but I have found that when I post a question non-anonymously, using Internet Explorer 9, I get this error:

"Can not find data record in database"

The debug info is shown below. It looks like the code is trying to find a course module with id = 0. It doesn't happen with Firefox, so perhaps it is something to with the way the browser is passing parameters?

Debug info: SELECT cm.*, m.name, md.name AS modname 
FROM {course_modules} cm
JOIN {modules} md ON md.id = cm.module
JOIN {hotquestion} m ON m.id = cm.instance

WHERE cm.id = :cmid AND md.name = :modulename

[array (
'cmid' => 0,
'modulename' => 'hotquestion',
)]

Stack trace: 
line 1300 of /lib/dml/moodle_database.php: dml_missing_record_exception thrown
line 1402 of /lib/datalib.php: call to moodle_database->get_record_sql()
line 43 of /mod/hotquestion/locallib.php: call to get_coursemodule_from_id()
line 40 of /mod/hotquestion/view.php: call to mod_hotquestion->__construct()
