### ISSUE TITLE
将界面AJAX化

### ISSUE THREAD

**Issue by sunner** [hit-moodle/moodle-mod_hotquestion#2]
将提问、投票操作AJAX化，不需刷新就显示最新结果。

界面整体实现遵从moodle 2.0的render机制：http://docs.moodle.org/en/Development:Output_renderers

AMOS的源码是个好参考：https://github.com/mudrd8mz/moodle-local_amos

**Comment by jerray** [comment]
在view.php中能否跳过$OUTPUT->header()和$OUTPUT->footer()，而只输出表单？
尝试了一下注释掉$OUTPUT->header()，页面会报错。

**Comment by sunner** [comment]
什么样的表单？如果是个正常的页面，header和footer都必须有的。如果是json一类的数据，可以在header前面输出，然后exit就行了

**Comment by jerray** [comment]
就是用来提交问题的表单，还有显示所有问题的表格。如果能直接输出它们的HTML代码，改起来会简单一些。

**Comment by sunner** [comment]
在header()之前输出应该差不多吧。可以看看amos的实现，路子差不多

**Comment by jerray** [comment]
是可以把header()放到页面最后输出的。在它前面加个exit就输出想要的表单了。这样一来可不可以这样做？——复制一份view.php仅输出提交问题和显示问题的表单，删去newround部分的代码。在hotquestion页面提问或者投票的时候，利用js将数据提交到这个新脚本。然后只要替换掉之前的表单再重新绑定DOM事件就可以了。

**Comment by sunner** [comment]
你的意思是单独弄一个xxxx.php处理所有ajax请求？当然可以，这样很好

**Comment by jerray** [comment]
嗯对，是这个意思。只要适当修改view.php就可以了。其余的就是写js脚本了。

**Comment by jerray** [comment]
任务完成 ^_______________^y

**Comment by sunner** [comment]
帅哦！这就学习学习去
