### ISSUE TITLE
增加一个刷新按钮

### ISSUE THREAD

**Issue by sunner** [hit-moodle/moodle-mod_hotquestion#3]
@7lemon ，ajax做得很帅！现在需要一个刷新按钮，只刷那个表格，否则用户还得刷新整个页面才能看到最新的问题后投票

**Comment by jerray** [comment]
把ajax.php实现的功能合并到view.php里了。
在描述和提交问题的表单中间加了一个刷新的链接。
看一下吧。样式好像需要改改，不怎么好看。包括页面提示信息的文字。

**Comment by sunner** [comment]
我这里看不到刷新按钮。而且提问时显示“网络错误。请检查网络连接或联系站点管理员”

**Comment by sunner** [comment]
刷新找到了，好高啊。应该在问题表格上面比较好

**Comment by jerray** [comment]
js文件会在浏览器里缓存。清一下缓存就可以了。
我再调整一下位置吧，顺便把样式归拢一下。

**Comment by sunner** [comment]
这个“刷新”不是ajax刷新吗？好像效果是刷新了整个页面啊

**Comment by jerray** [comment]
浏览器的问题，浏览器没有加载最新的actions.js
我已经为这个链接绑定事件了，js加载没问题的话就是只刷新表格

**Comment by sunner** [comment]
是缓存问题，解决了！
