### ISSUE TITLE
改为“真匿名”

### ISSUE THREAD

**Issue by sunner** [hit-moodle/moodle-mod_hotquestion#4]
现在的匿名提问并不是真的，数据库里还会记录用户id，只是在显示的时候显示为匿名。应该将其改为真匿名，不然不厚道。

**Comment by jerray** [comment]
Guest用户即可认为是匿名用户。做了一个简单的处理，如果用户勾选了匿名发布，则提交到数据库时，使用guest的ID即1。

**Comment by sunner** [comment]
这个解决方案很无敌！guest用户id肯定永远是1吗？看moodle里面是怎么使用guest id的，有没有什么专门函数用来获得这个

**Comment by jerray** [comment]
moodle在很多时候会对用户进行判断，看是否是访客用户。使用的函数是 isguestuser()。这个函数里面会查询数据库中username为guest的用户的ID，然后设置CFG->siteguest 为查询出的这个ID。在hotquestion能直接用这个值。

存入guest用户的id的办法，可以尽可能少地修改代码达到目的。但是如果数据库里不存在guest用户的话好像就麻烦了。
lib/accesslib.php 中第2801行的注释挺有意思（guest does not exist yet, weird）。

**Comment by sunner** [comment]
那就改成用CFG->siteguest好了，不用考虑不存在的情况，太极端
