### ISSUE TITLE
Not working with Moodle 2.1

### ISSUE THREAD

**Issue by philpav** [hit-moodle/moodle-mod_hotquestion#7]
Please update the module to make it work with Moodle 2.1.  Submitting a question doesn't do anything.
I really would like to test it. Could be quite useful here. 

Thank you!

**Comment by sunner** [comment]
I'm using it with Moodle 2.1 and it works well. What's problem did you meet? Is there any error message? You install the plugin totally new or upgrade from old version? Thanks.

**Comment by philpav** [comment]
That's really weird then. 
I've installed the plugin totally new without any errors. 
But when I enter a question an click on "Post" the button just grays out and nothing happens. 
The debugging is set to developer but no error message appears. 
I've tried following browser without luck: Opera 12 (alpha), IE6, IE9, Chrome 11
I tried two Moodle 2.1 weekly instances: one under WinXP XAMPP and one under UNIX (Apache)

**Comment by sunner** [comment]
Ya, so weird! Is your site accessible for me? If yes, tell me how by email to sunner@gmail.com.

**Comment by sunner** [comment]
Another question: after clicking post button, refresh the whole page, can you see the question?

**Comment by philpav** [comment]
The question doesn't appear. 
I've sent you an email. 

Thanks a lot!

**Comment by philpav** [comment]
I'm really sorry. 
I've just found out why it's not working. 

The hot question activity must be added to a topic. 
I've always added it to the top of the course and it's not working there. 

I don't if this is the intended behavior.

Sorry again for the circumstances!

**Comment by sunner** [comment]
Hot question should work in the general topic. It is a bug really. I will fix it. Thanks for report

**Comment by philpav** [comment]
That's been fast!
Thanks a lot!
